name: Ottsonic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9581
title: Ottsonic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050000'
    - '#ffffff'
    - '#463d40'
    - '#c4b2ae'
    - '#007a9c'
  brandStrength: 0.5
  lightness: 0.8013207286130637
  saturation: 0.5409154077060521
  rhythmicContrast: 0.2501785606145859
purpose: []
