name: Ottsonic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23187
title: Ottsonic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050000'
    - '#ffffff'
    - '#463d40'
    - '#c4b2ae'
    - '#007a9c'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
