name: Ottsonic
favicon: null
layout_spectrum: 0.09732171730138361
typography_spectrum: 0.3892847499810159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.38126803981140256
  lightness: 0.8013207286130637
  saturation: 0.5409154077060521
  rhythmicContrast: 0.2501785606145859
purpose: []
