name: Ottsonic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22405
title: Ottsonic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9fc54c'
    - '#ffffff'
    - '#a975ad'
    - '#e2b13e'
    - '#e4d2e2'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
